version: '3.8'

services:
 eventsapi:
  build:
   context: .
  ports:
   - 5500:5500
  environment:
   - CONN_STRING=postgresql://postgres:${PGPASSWORD}@postgresdb:5432/postgres
  volumes:
   - ./:/app
  command: npm run dev

 postgresdb:
  image: postgres:alpine
  ports:
   - 5432:5432
  environment:
   - POSTGRES_PASSWORD=${PGPASSWORD}
  volumes:
   - pgdb:/var/lib/postgresql/data
volumes:
 pgdb:
